# Site settings
title: Code . data sciences
email: hadrienjean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://hadrienj.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  hadrienj
disqus_username:

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
tag_page: '/tags'
